### PR TITLE
Sphinx documentation + ReadTheDocs public repository + Main commands + Auto Import Improvements

### PR DESCRIPTION
**Pull request by DamnWidget**
Hi folks.

I just added Sphinx documentation that can be built using 'make html' in the docs repository. I created a RedTheDocs public site that is pointing to my Git repo now (but should point to Julian main repo when commit get merged).

I added a main commands file as well for doc and usability purposes.

You can check the new main repo README here https://github.com/DamnWidget/SublimeRope  and the online documentation here https://sublimerope.rtfd.org/

This repo has a hook URL to perform auto updates of the documentation on Git repo push, this should be set in Julian main repo as well.

P.D: Some native english speecher should check my crappy english.

Regards.

### CODE REVIEW

**Comment by DamnWidget** [comment]
I just add a new Feature:

Auto Import Improvements

When Auto Import Improvements are enabled all the undefined words in the current file should be checked on file save (in a different thread) looking for an auto import for them. If SublimeRope finds a possible autoimport for them should show you so you can choose it and the import will be automatically applied to your file.

You can disable Auto Import Improvements in your SublimeRope’s settings file just setting the use_autoimport_improvements to false if you feels that its slowing down your ST2

Regards.

**Comment by JulianEberius** [comment]
Wow just checked the documentation you wrote, seems like a lot of work went into this. Thanks a lot!

About the autoimport: seems like a nice feature, but do we really have to include PyFlakes for this?
Rope already parses the code, maybe there is some point in Rope where UndefinedNames can be identified.
On the other hand: if we include PyFlakes, then we could also go all the way and integrate PyLinter/SublimeLinter like "show errors" functionality with SublimeRope to turn it into a one-stop Python solution. At the moment I use SublimeRope+PyLinter for my Python work. 

Well I guess I really need to free some time for SublimeRope ;-)
Thanks again!

**Comment by DamnWidget** [comment]
Yeah, I was already wondering if Rope doesn't offer some way to perform auto import operations in missing definitions by itself.

I'm going to do a rollback to the 1b239c256a52cb7195264636b5b5bb7db9574138 commit so you can merge the documentation thing.

Regards.

**Comment by JulianEberius** [comment]
No it's ok, i just merged the whole thing, it's disabled by default, so no harm done for current users, and a new feature is always nice ;-)

**Pull request merged**
